delete from mst_news;
insert into mst_news (role_id, subject, url, version) values('ROLE_ADMIN', '表題テスト1', 'http://hoge/test1', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_ADMIN', '表題テスト2', 'http://hoge/test2', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト1', 'http://hogehoge/test1', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト2', 'http://hogehoge/test2', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト3', 'http://hogehoge/test3', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト4', 'http://hogehoge/test4', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト5', 'http://hogehoge/test5', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト6', 'http://hogehoge/test6', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト7', 'http://hogehoge/test7', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト8', 'http://hogehoge/test8', 0);
insert into mst_news (role_id, subject, url, version) values('ROLE_USER', 'テスト表題テスト9', 'http://hogehoge/test9', 0);
